### ISSUE TITLE
Bullets erratic on mobile app

### ISSUE THREAD

**Issue by psychsatani** [chetachiezikeuzor/Yin-and-Yang-Theme#25]
I have attached two videos. One with the theme turned on. It shows the bullets do random things (it's different each time) with end result is that I can't use them. This issue resolved when I turn the theme off (other video). https://user-images.githubusercontent.com/78266798/126027035-5a0751e7-0ab7-4e44-b18a-0a7409d619ec.MOV
https://user-images.githubusercontent.com/78266798/126027023-bc722cf9-b3ff-4ca2-a398-be83ee54be42.MOV

**Comment by chetachiezikeuzor** [comment]
Do you have Enhanced Typography toggled on? And when did you last install the theme?

**Comment by chetachiezikeuzor** [comment]
Should be fixed now! 👍🏽

**Comment by psychsatani** [comment]
I installed a week ago. Tweaked a few settings a couple of days ago. Noticed this issue only today but I might not have used bullets in the last few days on the mobile. 

The issue is not fixed for me. I killed the app, switched themes and checked. Should I do something else?

**Comment by chetachiezikeuzor** [comment]
Have you reinstalled the theme?

**Comment by psychsatani** [comment]
Just reinstalled the theme. It is fixed. Thanks a ton for this wonderful theme!!

**Comment by chetachiezikeuzor** [comment]
Wonderful, and thank you! Have a lovely day!
